name: story_carousel
description: Instagram-like stories carousel for Flutter with auto-advance, gestures and progress indicators.
version: 0.1.0
homepage: https://github.com/anarvaezf/flutter_story_carousel
repository: https://github.com/anarvaezf/flutter_story_carousel
issue_tracker: https://github.com/anarvaezf/flutter_story_carousel/issues
topics:
  - carousel
  - stories
  - ui
  - widgets

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Images to show on pub.dev (place files under /assets)
screenshots:
  - description: Light theme demo
    path: assets/screenshot_light.png
  - description: Dark theme demo
    path: assets/screenshot_dark.png

flutter:
  # No runtime assets needed for the package itself